# Generated by Django 4.2.1 on 2023-05-31 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('victories', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='drawmatch_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('id_user_left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left', to='drawmatch_app.users')),
                ('id_user_right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right', to='drawmatch_app.users')),
            ],
        ),
    ]
