# Generated by Django 4.2.1 on 2023-05-31 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawmatch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerooms',
            name='id_user_left',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left', to='drawmatch_app.users'),
        ),
        migrations.AlterField(
            model_name='activerooms',
            name='id_user_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right', to='drawmatch_app.users'),
        ),
    ]
