# Generated by Django 4.2.1 on 2023-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawmatch_app', '0002_alter_activerooms_id_user_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerooms',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
