# Generated by Django 4.2.1 on 2023-06-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawmatch_app', '0003_alter_activerooms_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerooms',
            name='id_user_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activerooms',
            name='id_user_right',
            field=models.IntegerField(null=True),
        ),
    ]
