# Generated by Django 4.2.1 on 2023-06-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawmatch_app', '0005_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerooms',
            name='id_user_left',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_user_left', to='drawmatch_app.users'),
        ),
        migrations.AlterField(
            model_name='activerooms',
            name='id_user_right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_user_right', to='drawmatch_app.users'),
        ),
    ]
