# Generated by Django 4.2.1 on 2023-06-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawmatch_app', '0006_alter_activerooms_id_user_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='victories',
        ),
        migrations.CreateModel(
            name='Victories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='drawmatch_app.users')),
            ],
        ),
    ]
