# Generated by Django 4.2.1 on 2023-06-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawmatch_app', '0007_remove_users_victories_victories'),
    ]

    operations = [
        migrations.AddField(
            model_name='victories',
            name='room_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='drawmatch_app.activerooms'),
        ),
    ]
