# Generated by Django 4.2.1 on 2023-06-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawmatch_app', '0012_alter_victories_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='drawmatch_app.activerooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='drawmatch_app.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Victories',
        ),
    ]
